### ISSUE TITLE
cy.focused().type("text") shows cypress/unsafe-to-chain-command error

### ISSUE THREAD

**Issue by BCaspari** [cypress-io/eslint-plugin-cypress#140] opened 2023-08-09 09:50 UTC
After an update to 2.14.0, the  cypress/unsafe-to-chain-command rule is triggered by code as
`cy.focused().type("text")`.
This should be no problem however, as the cypress docu states `cy.focused() is a query, and it is safe to chain further commands` (https://docs.cypress.io/api/commands/focused)

**Comment by nagash77** [comment] 2023-08-09 12:48
Hi @BCaspari , you are correct that `cy.focused` is a query and safe to chain off of.  `cy.focus` is however not safe to chain off of.  I believe this might be an overzealous match from [this PR](https://github.com/cypress-io/eslint-plugin-cypress/commit/49c6eb32fa4becc276599697b733815264d71754).  Thank you for reporting this issue.  I am not sure when we will be able to address this issue, so for the time being I would suggest downgrading and pinning your version to avoid this problem.

**Comment by MikeMcC399** [comment] 2023-08-09 15:23
This would also impact [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink) if it weren't for the fact that `unsafe-to-chain` linting is currently disabled in that repo.

- See https://github.com/cypress-io/cypress-example-kitchensink/issues/661#issuecomment-1671098740

**Comment by lgenzelis** [comment] 2023-08-14 12:15
Even doing `cy.focused().blur()`, which [is an example given in the docs](https://docs.cypress.io/api/commands/focused#Blur-the-element-with-focus) raises this error now.

**Comment by code-jorge** [comment] 2023-08-16 12:06
I believe this to be an unintended side effect from this change specifically:

https://github.com/cypress-io/eslint-plugin-cypress/commit/49c6eb32fa4becc276599697b733815264d71754#diff-43276831483080b5e9f5d83eb749bebf8e0d7167aa50c64cbc4fc1bcd7e0698bR121

Which comes from here:

https://github.com/cypress-io/eslint-plugin-cypress/commit/49c6eb32fa4becc276599697b733815264d71754#diff-43276831483080b5e9f5d83eb749bebf8e0d7167aa50c64cbc4fc1bcd7e0698bR111-R115

Seems like before this change, any selector had to exactly match the name of the "unsafe to chain" selectors. Now, because of the regex, if the selector's name partially matches one of the names, the linter will complain.

e.g. `/focus/.test("focused")` returns `true`, so the linter complains.

**Comment by ext** [comment] 2023-09-13 14:54
Any progress on this one? Is there anything I could do to help? The issue and the cause seems to be identified.

**Comment by dominicfraser** [comment] 2023-09-15 16:18
I've made a PR to illustrate the false positive, and a potential fix, here: https://github.com/cypress-io/eslint-plugin-cypress/pull/142

**Comment by MikeMcC399** [comment] 2023-09-20 13:43
@dominicfraser 

- Since your PR #142 has been merged, can this issue now be closed?

**Comment by dominicfraser** [comment] 2023-09-26 10:17
I believe so yes ☺️ 

A more scalable solution is proposed in https://github.com/cypress-io/eslint-plugin-cypress/pull/141 (rather than the fast hotfix I did) - but for this specific bug the merged PR and new release solves it adequately 👍

**Comment by dominicfraser** [comment] 2023-09-26 10:17
https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v2.15.1 specifically

**Comment by imaliouris** [comment] 2023-10-03 07:02
the implementation is wrong.. Not only focused but every command that contains any of the unsafe to chain commands shows cypress/unsafe-to-chain-command error. 
i.e. custom command submitBtn shows cypress/unsafe-to-chain-command error.

Please check https://github.com/cypress-io/eslint-plugin-cypress/pull/141 because we have to rename our functions or disable linting and that's not the proper solution..

**Comment by MikeMcC399** [comment] 2024-05-02 11:31
- This issue is resolved by PR #141

**Closed** 2024-05-03 18:01 UTC
Labels: bug, triaged, E2E
